ingress:
  enabled: false
  hosts:
    - host: chart-example.local
      paths: [
        "/api/v1/products"
      ]
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux