name: Report a bug 🐛
description: Create a report to help us improve
labels: "bug"
body:
- type: textarea
  attributes:
    label: Report
    description: "What bug have you encountered?"
    placeholder: "A clear and concise description of what the bug is."
- type: textarea
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
    placeholder: What did you expect to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual Behavior
    description: Also tell us, what did you see is happen?
    placeholder: Tell us what you see that is happening
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to Reproduce the Problem
    description: "How can we reproduce this bug? Please walk us through it step by step."
    value: |
      1.
      2.
      3.
  validations:
    required: true
- type: textarea
  id: version
  attributes:
    label: Self-hosted Gateway Version
    description: "What version of the self-hosted gateway are you running?"
  validations:
    required: true
- type: textarea
  attributes:
    label: Logs from self-hosted gateway
    description: "Provide logs from self-hosted gateway, if need be."
    value: |
      ```
      example
      ```
  validations:
    required: true
- type: dropdown
  attributes:
    label: Kubernetes Version
    description: What version of Kubernetes that are you running?
    options:
    - "1.22"
    - "1.21"
    - "1.20"
    - "1.19"
    - "1.18"
    - "1.17"
    - "< 1.17"
    - "Other"
  validations:
    required: false
- type: dropdown
  attributes:
    label: Platform
    description: Where is your cluster running?
    options:
    - Any
    - Alibaba Cloud
    - Amazon Web Services
    - Google Cloud
    - Microsoft Azure
    - Red Hat OpenShift
    - Other
  validations:
    required: false
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: "Let us know if you have anything else to share"
