apiVersion: v2
version: 1.14.1
appVersion: 2.10.1
# Specify the Kubernetes version range that we support.
# We allow pre-release versions for cloud-specific Kubernetes versions such as  v1.21.5-gke.1302 or v1.18.9-eks-d1db3c
kubeVersion: ">=v1.20.0-0"
name: azure-api-management-gateway
description: A Helm chart to deploy the self-hosted gateway of Azure API Management on Kubernetes
home: https://docs.microsoft.com/azure/api-management/self-hosted-gateway-overview
sources:
  - https://github.com/Azure/api-management-self-hosted-gateway
  - https://mcr.microsoft.com/product/azure-api-management/gateway/about
  - https://docs.microsoft.com/azure/api-management/self-hosted-gateway-overview
maintainers:
  - name: Azure API Management Team
    url: https://github.com/Azure/api-management-self-hosted-gateway
  - name: Vlad Vinogradsky
    url: https://github.com/vladvino
  - name: Tom Kerkhove
    url: https://github.com/tomkerkhove
icon: https://github.com/Azure/API-Management/raw/main/media/apim-logo.png
keywords:
  - api-management
  - api-gateway
  - self-hosted-gateway
  - azure
  - ingress
  - Microsoft Azure
  - Azure
  - APIs
  - API Monetization
  - API Ecosystem
  - API Gateway
  - API Management
  - Cloud
  - Multi-Cloud
  - Hybrid
  - Kubernetes
  - Cloud-Native
  - gRPC
  - GraphQL
  - REST
  - OData
  - SOAP
  - AI
  - GenAI
  - Generative AI
  - Artificial Intelligence
