apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "azure-api-management-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
    helm.sh/chart: {{ include "azure-api-management-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{ if .Values.dapr.enabled -}}
      annotations:
        dapr.io/enabled: "true"
        {{ if .Values.dapr.appId -}}
        dapr.io/app-id: {{ .Values.dapr.appId | quote }}
        {{ end }}
      {{ end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8081
          env:
          - name: config.service.auth
            valueFrom:
              secretKeyRef:
                name: {{ include "azure-api-management-gateway.fullname" . }}
                key: gateway-key
          envFrom:
          - configMapRef:
              name: {{ include "azure-api-management-gateway.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
