{{- if .Values.secret.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-api-management-gateway.fullname" . }}
  labels:
    {{- include "azure-api-management-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  gateway-key: {{ .Values.gateway.auth.key | b64enc | quote }}
{{- end }}
