apiVersion: v1
kind: Service
metadata:
  name: {{ include "azure-api-management-gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
    helm.sh/chart: {{ include "azure-api-management-gateway.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "azure-api-management-gateway.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
