name: Helm Chart CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  lint-helm-3-x:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Helm install
      uses: Azure/setup-helm@v1

    - name: Lint 'azure-api-management-gateway' Helm chart
      # We are using dummy gateway parameters here just to show how you can pass them as they are required
      run: helm lint helm-charts/azure-api-management-gateway --set gateway.configuration.uri="xyz.configuration.azure-api.net" --set gateway.auth.key="GatewayKey xyz"

  deploy-helm-3-x:
    runs-on: ubuntu-latest
    needs: lint-helm-3-x
    strategy:
      fail-fast: false
      matrix:
        enableHighAvailability: [false, true]
        kubernetesVersion: [v1.24, v1.23, v1.22, v1.21, v1.20]
        include:
          # Images are defined on every Kind release
          # See https://github.com/kubernetes-sigs/kind/releases for an overview of the images
        - kubernetesVersion: v1.24
          kindImage: kindest/node:v1.24.0@sha256:406fd86d48eaf4c04c7280cd1d2ca1d61e7d0d61ddef0125cb097bc7b82ed6a1
        - kubernetesVersion: v1.23
          kindImage: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355
        - kubernetesVersion: v1.22
          kindImage: kindest/node:v1.22.9@sha256:6e57a6b0c493c7d7183a1151acff0bfa44bf37eb668826bf00da5637c55b6d5e
        - kubernetesVersion: v1.21
          kindImage: kindest/node:v1.21.12@sha256:ae05d44cc636ee961068399ea5123ae421790f472c309900c151a44ee35c3e3e
        - kubernetesVersion: v1.20
          kindImage: kindest/node:v1.20.15@sha256:a6ce604504db064c5e25921c6c0fffea64507109a1f2a512b1b562ac37d652f3
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }} (${{ (matrix.enableHighAvailability == true && 'With HA') || 'Without HA' }})
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Authenticate to Azure
      uses: azure/login@v1
      with:
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ secrets.AZURE_CI_CLIENT_ID }}

    - name: Get gateway secrets from Azure Key Vault
      id: fetched-secrets
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          GATEWAY_CONFIG_URL=$(az keyvault secret show --name "Gateway-Configuration-Url" --vault-name "${{ secrets.AZURE_KEY_VAULT_NAME }}" --query "value")
          GATEWAY_TOKEN=$(az keyvault secret show --name "Gateway-Token" --vault-name "${{ secrets.AZURE_KEY_VAULT_NAME }}" --query "value")
          echo "::set-output name=configurationUrl::$GATEWAY_CONFIG_URL"
          echo "::add-mask::$GATEWAY_TOKEN"
          echo "::set-output name=gatewayToken::$GATEWAY_TOKEN"

    - name: Helm install
      uses: Azure/setup-helm@v1
      
    - name: Create k8s ${{ matrix.kubernetesVersion }} Kind Cluster
      uses: helm/kind-action@v1.2.0
      with:
        version: v0.13.0
        node_image: ${{ matrix.kindImage }}

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Show Helm version
      run: |
        helm version

    - name: Create Kubernetes namespace
      run: kubectl create ns apim-gateway

    - name: Template Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.key=${{ steps.fetched-secrets.outputs.gatewayToken }} --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --values ./test-config.yml --dry-run

    - name: Install Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.key=${{ steps.fetched-secrets.outputs.gatewayToken }} --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --values ./test-config.yml --wait --timeout 10m0s

    - name: Show Kubernetes resources
      run: kubectl get all --namespace apim-gateway
      if: always()

    - name: Show Logs for Self-Hosted Gateway
      run: kubectl logs -l app.kubernetes.io/name=azure-api-management-gateway --namespace apim-gateway
      if: always()
