name: Helm Chart CI (Main)
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  AZURE_SUBSCRIPTION_ID: a200340d-6b82-494d-9dbf-687ba6e33f9e
  AZURE_CI_CLIENT_ID: 359b42a2-78a3-49e7-9be3-6ddfd1a27329

jobs:
  deploy-gateway-token:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        enableHighAvailability: [false, true]
        kubernetesVersion: [v1.36, v1.35, v1.34, v1.33]
        include:
          # Images are defined on every Kind release
          # See https://github.com/kubernetes-sigs/kind/releases for an overview of the images
        - kubernetesVersion: v1.36
          kindImage: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
        - kubernetesVersion: v1.35
          kindImage: kindest/node:v1.35.5@sha256:ce977ae6d65918d0b58a5f8b5e940429c2ce42fa3a5619ec2bbc60b949c0ac95
        - kubernetesVersion: v1.34
          kindImage: kindest/node:v1.34.8@sha256:02722c2dedddcfc00febf5d27fbeb9b7b2c14294c82109ff4a85d89ac9ba3256
        - kubernetesVersion: v1.33
          kindImage: kindest/node:v1.33.12@sha256:3f5c8443c620245e4d355cfe09e96a91ead32ceaa569d3f1ca9edf0cb2fe2ff4
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }} (${{ (matrix.enableHighAvailability == true && 'With HA') || 'Without HA' }})
    steps:
    - name: Check out code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        fetch-depth: 0

    - name: Authenticate to Azure
      uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
      with:
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ env.AZURE_CI_CLIENT_ID }}

    - name: Get gateway secrets from Azure Key Vault
      id: fetched-secrets
      uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          GATEWAY_CONFIG_URL=$(az keyvault secret show --name "Gateway-Configuration-Url" --vault-name "${{ vars.AZURE_KEY_VAULT_NAME }}" --query "value")
          GATEWAY_TOKEN=$(az keyvault secret show --name "Gateway-Token" --vault-name "${{ vars.AZURE_KEY_VAULT_NAME }}" --query "value")
          echo "::set-output name=configurationUrl::$GATEWAY_CONFIG_URL"
          echo "::add-mask::$GATEWAY_TOKEN"
          echo "::set-output name=gatewayToken::$GATEWAY_TOKEN"

    - name: Helm install
      uses: Azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
      
    - name: Create k8s ${{ matrix.kubernetesVersion }} Kind Cluster
      uses: helm/kind-action@94729529f85113b88f4f819c17ce61382e6d8478 # v1.2.0
      with:
        version: v0.32.0
        node_image: ${{ matrix.kindImage }}
        config: ./testing/kind-cluster.yml

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Describe Control-Plane Node
      run: |
        kubectl describe nodes/chart-testing-control-plane

    - name: Describe Worker Node
      run: |
        kubectl describe nodes/chart-testing-worker

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Show Helm version
      run: |
        helm version

    - name: Create Kubernetes namespace
      run: kubectl create ns apim-gateway

    - name: Template Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.key=${{ steps.fetched-secrets.outputs.gatewayToken }} --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --set gateway.deployment.strategy.type=Recreate --values ./testing/test-config.yml --dry-run

    - name: Install Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.key=${{ steps.fetched-secrets.outputs.gatewayToken }} --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --set gateway.deployment.strategy.type=Recreate --values ./testing/test-config.yml --wait --timeout 10m0s

    - name: Show Kubernetes resources
      run: kubectl get all --namespace apim-gateway
      if: always()

    - name: Show Logs for Self-Hosted Gateway
      run: kubectl logs -l app.kubernetes.io/name=azure-api-management-gateway --namespace apim-gateway
      if: always()

  deploy-azure-ad:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        enableHighAvailability: [false, true]
        kubernetesVersion: [v1.36, v1.35, v1.34, v1.33]
        include:
          # Images are defined on every Kind release
          # See https://github.com/kubernetes-sigs/kind/releases for an overview of the images
        - kubernetesVersion: v1.36
          kindImage: kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
        - kubernetesVersion: v1.35
          kindImage: kindest/node:v1.35.5@sha256:ce977ae6d65918d0b58a5f8b5e940429c2ce42fa3a5619ec2bbc60b949c0ac95
        - kubernetesVersion: v1.34
          kindImage: kindest/node:v1.34.8@sha256:02722c2dedddcfc00febf5d27fbeb9b7b2c14294c82109ff4a85d89ac9ba3256
        - kubernetesVersion: v1.33
          kindImage: kindest/node:v1.33.12@sha256:3f5c8443c620245e4d355cfe09e96a91ead32ceaa569d3f1ca9edf0cb2fe2ff4
    name: Deploy to Kubernetes ${{ matrix.kubernetesVersion }} (${{ (matrix.enableHighAvailability == true && 'With HA') || 'Without HA' }})
    steps:
    - name: Check out code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      with:
        fetch-depth: 0

    - name: Authenticate to Azure
      uses: azure/login@cb79c773a3cfa27f31f25eb3f677781210c9ce3d # v1.6.1
      with:
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        client-id: ${{ env.AZURE_CI_CLIENT_ID }}

    - name: Get gateway secrets from Azure Key Vault
      id: fetched-secrets
      uses: azure/CLI@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1.0.9
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          GATEWAY_CONFIG_URL=$(az keyvault secret show --name "Gateway-Configuration-Url" --vault-name "${{ vars.AZURE_KEY_VAULT_NAME }}" --query "value")
          AD_APP_SECRET=$(az keyvault secret show --name "Azure-Ad-App-Secret" --vault-name "${{ vars.AZURE_KEY_VAULT_NAME }}" --query "value")
          echo "::set-output name=configurationUrl::$GATEWAY_CONFIG_URL"
          echo "::add-mask::$AD_APP_SECRET"
          echo "::set-output name=adAppSecret::$AD_APP_SECRET"

    - name: Helm install
      uses: Azure/setup-helm@18bc76811624f360dbd7f18c2d4ecb32c7b87bab # v1.1
      
    - name: Create k8s ${{ matrix.kubernetesVersion }} Kind Cluster
      uses: helm/kind-action@94729529f85113b88f4f819c17ce61382e6d8478 # v1.2.0
      with:
        version: v0.32.0
        node_image: ${{ matrix.kindImage }}
        config: ./testing/kind-cluster.yml

    - name: Show Kubernetes version
      run: |
        kubectl version

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Describe Control-Plane Node
      run: |
        kubectl describe nodes/chart-testing-control-plane

    - name: Describe Worker Node
      run: |
        kubectl describe nodes/chart-testing-worker

    - name: Show Kubernetes nodes
      run: |
        kubectl get nodes -o wide

    - name: Show Helm version
      run: |
        helm version

    - name: Create Kubernetes namespace
      run: kubectl create ns apim-gateway

    - name: Template Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.type=AzureAdApp --set gateway.name=${{ vars.GATEWAY_NAME }} --set gateway.auth.azureAd.tenant.id=${{ env.AZURE_TENANT_ID }} --set gateway.auth.azureAd.app.id=${{ env.AZURE_CI_CLIENT_ID }} --set gateway.auth.azureAd.app.secret=${{ steps.fetched-secrets.outputs.adAppSecret }}  --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --set gateway.deployment.strategy.type=Recreate --values ./testing/test-config.yml --dry-run

    - name: Install Helm chart
      run: helm install azure-api-management-gateway ./helm-charts/azure-api-management-gateway --namespace apim-gateway --set gateway.configuration.uri=${{ steps.fetched-secrets.outputs.configurationUrl }} --set gateway.auth.type=AzureAdApp --set gateway.name=${{ vars.GATEWAY_NAME }} --set gateway.auth.azureAd.tenant.id=${{ env.AZURE_TENANT_ID }} --set gateway.auth.azureAd.app.id=${{ env.AZURE_CI_CLIENT_ID }} --set gateway.auth.azureAd.app.secret=${{ steps.fetched-secrets.outputs.adAppSecret }} --set highAvailability.enabled=${{ matrix.enableHighAvailability }} --set gateway.deployment.strategy.type=Recreate --values ./testing/test-config.yml --wait --timeout 10m0s

    - name: Show Kubernetes resources
      run: kubectl get all --namespace apim-gateway
      if: always()

    - name: Show Logs for Self-Hosted Gateway
      run: kubectl logs -l app.kubernetes.io/name=azure-api-management-gateway --namespace apim-gateway
      if: always()
